create user ashlogger identified by "ashlogger";
grant create session            to ashlogger;
grant select on dba_data_files  to ashlogger;
grant select on dba_free_space  to ashlogger;
grant select on v_$sysstat      to ashlogger;
grant select on v_$sysstat      to ashlogger;
grant select on v_$session      to ashlogger;
grant select on v_$system_event to ashlogger;
grant select on v_$parameter    to ashlogger;
grant select on v_$database     to ashlogger;
grant select on v_$license      to ashlogger;
grant select on dba_segments    to ashlogger;
grant select on dba_temp_files  to ashlogger;
